version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=db
    ports:
    - "5432:5432"
    
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONBUFFERED=1
      - DJANGO_SETTINGS_MODULE=private_diary.settings_dev
    depends_on:
      - db